export const capacitacoesSeed = [
  {
    srl_trilha: 'Painel Deep Tech',
    tema: 'Dinâmica Pitch Elevador',
    palestrante: 'Esthefany França',
    data: '',
    horario: '09:30',
  },
  {
    srl_trilha: 'Painel Deep Tech',
    tema: 'Onco IA',
    palestrante: 'Onco IA',
    data: '',
    horario: '10:00',
  },
  {
    srl_trilha: 'Painel Deep Tech',
    tema: 'Da academia ao mercado',
    palestrante: 'Brennda',
    data: '',
    horario: '10:30',
  },
  {
    srl_trilha: 'Painel Deep Tech',
    tema: 'Oportunidades Abstartups e Sebrae',
    palestrante: 'André',
    data: '',
    horario: '11:00',
  },
  {
    srl_trilha: 'Painel Comunicação',
    tema: 'Comunicação assertiva',
    palestrante: 'Renan Santos',
    data: '',
    horario: '14:30',
  },
  {
    srl_trilha: 'Painel Comunicação',
    tema: 'Negociação e Vendas',
    palestrante: 'Leonardo Raupp',
    data: '',
    horario: '15:00',
  },
  {
    srl_trilha: 'Painel Comunicação',
    tema: 'O Poder da Comunicação',
    palestrante: 'Dione Aguiar',
    data: '',
    horario: '16:00',
  },
  {
    srl_trilha: 'Online',
    tema: 'Modelos de Negócio',
    palestrante: 'Caio Stettiner',
    data: '02/05',
    horario: '',
  },
  {
    srl_trilha: 'Online',
    tema: 'IA para marketing digital',
    palestrante: 'Luiz Chiavini',
    data: '30 julho',
    horario: '',
  },
  {
    srl_trilha: 'Online',
    tema: 'Editais de fomento',
    palestrante: '—',
    data: '',
    horario: '',
  },
]
