export const mentoriasSeed = [
  {
    startup: 'Pluralgae',
    responsavel_startup: 'Mariana Fortes',
    area_mentoria: 'Editais de Fomento',
    mentor: 'Elisa Maia de Godoy',
    data_solicitacao: '',
    status: 'Concluída',
    data_agendamento: '',
    data_mentoria: '01/07',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'Explores do Porquê Educação Científica',
    responsavel_startup: 'Sara Nállia',
    area_mentoria: 'Contábil',
    mentor: 'Kaio Guilherme de Oliveira Gallo',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '04/05',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'AZB Environment Sampling',
    responsavel_startup: 'André Zuffo Buoratti',
    area_mentoria: 'Jurídico',
    mentor: 'Antony Jefferson',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '16/06',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'Nexus Cidadão',
    responsavel_startup: 'Yuri Leite',
    area_mentoria: 'Marketing e Vendas',
    mentor: 'Victor Yagyu',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '18/06',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'FWS Consultoria',
    responsavel_startup: 'Daniel Santiago Rucinque',
    area_mentoria: 'Jurídico',
    mentor: 'Juliana Duarte Vieira Amaral',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '22/06',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'FWS Consultoria',
    responsavel_startup: 'Daniel Santiago Rucinque',
    area_mentoria: 'Finanças',
    mentor: 'Felipe Andre Junqueira',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '22/06',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
  {
    startup: 'FWS Consultoria',
    responsavel_startup: 'Daniel Santiago Rucinque',
    area_mentoria: 'Processos',
    mentor: 'Tavani Rocha Camargo',
    data_solicitacao: '',
    status: 'Agendada',
    data_agendamento: '',
    data_mentoria: '22/06',
    relatorio_recebido: '',
    pagamento_mentor: '',
    observacoes: '',
  },
]
